package com.example.memo.entity;

import java.io.Serializable;

import com.example.memo.utlis.SildeView;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTE.
 */
@SuppressWarnings("serial")
public class Note implements Serializable{

	private Integer id;
	private String name;
	private String date;
	private String Vlue;
	public SildeView slideView;


	public Note() {
		
	}

	public Note(Integer id, String name, String date, String Vlue) {
		this.id = id;
		this.name = name;
		this.date = date;
		this.Vlue = Vlue;
	}


	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getVlue() {
		return Vlue;
	}

	public void setVlue(String Vlue) {
		this.Vlue = Vlue;
	}

	@Override
	public String toString() {
		return "Note [id=" + id + ", name=" + name + ", date=" + date
				+ ", Vlue=" + Vlue + "]";
	}
}
